-- Run once in a NEW lab_work.db, never in chinook.db.
PRAGMA foreign_keys = ON;
CREATE TABLE programme(programme_id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL);
INSERT INTO programme VALUES ('CS','Computer Science'),('DS','Data Science'),('EE','Electronic Engineering');
CREATE TABLE student(student_id INTEGER PRIMARY KEY, name TEXT NOT NULL, year INTEGER NOT NULL CHECK(year BETWEEN 1 AND 4), prog_code TEXT REFERENCES programme(programme_id));
INSERT INTO student VALUES (1111,'Chan Ada',1,'CS'),(1112,'Ben Lee',1,'DS'),(1113,'Chan Cara',2,'CS'),(1114,'Dev Wu',3,'EE'),(1115,'Eli Lin',3,NULL),(1116,'Fay Ho',4,'DS');
CREATE TABLE graduate_list(student_id INTEGER PRIMARY KEY);
INSERT INTO graduate_list VALUES(1116);
CREATE TABLE company3(id INTEGER PRIMARY KEY, name TEXT NOT NULL CHECK(length(name)>=5), address TEXT, salary REAL CHECK(salary>0));
CREATE TABLE products(product_id INTEGER PRIMARY KEY, product_name TEXT NOT NULL, list_price REAL NOT NULL, discount REAL NOT NULL DEFAULT 0, CHECK(list_price>=discount AND discount>=0 AND list_price>=0));
INSERT INTO products VALUES(1,'SQLite Guide',30,5);
CREATE TABLE company4(id INTEGER PRIMARY KEY, name TEXT NOT NULL);
INSERT INTO company4 VALUES(1,'Alpha'),(2,'Beta'),(3,'Gamma');
CREATE TABLE item_restrict(item_id INTEGER PRIMARY KEY,item_desc TEXT NOT NULL,com_id INTEGER NOT NULL REFERENCES company4(id) ON UPDATE RESTRICT ON DELETE RESTRICT);
INSERT INTO item_restrict VALUES(1,'Keyboard',1);
CREATE TABLE item_setnull(item_id INTEGER PRIMARY KEY,item_desc TEXT NOT NULL,com_id INTEGER REFERENCES company4(id) ON UPDATE SET NULL ON DELETE SET NULL);
INSERT INTO item_setnull VALUES(1,'Monitor',2);
CREATE TABLE alter_demo(id INTEGER PRIMARY KEY,name TEXT);
INSERT INTO alter_demo VALUES(1,'Ada');
CREATE TABLE books(book_id INTEGER PRIMARY KEY,title TEXT NOT NULL,publication_year TEXT);
INSERT INTO books VALUES(0,'Book A','2013'),(1,'Book B','2014');
CREATE TABLE staff_migration(employee_id INTEGER PRIMARY KEY,first_name TEXT,last_name TEXT);
INSERT INTO staff_migration VALUES(1,'Ada','Chan'),(2,'Ben',NULL);
CREATE TABLE Queue(person_id INTEGER PRIMARY KEY,person_name TEXT NOT NULL,weight INTEGER NOT NULL CHECK(weight>0),turn INTEGER NOT NULL UNIQUE);
INSERT INTO Queue VALUES(1,'Alice',250,1),(2,'Bob',175,2),(3,'Cara',400,3),(4,'Dan',200,4);
CREATE TABLE Department(id INTEGER PRIMARY KEY,name TEXT NOT NULL);
INSERT INTO Department VALUES(1,'IT'),(2,'Sales'),(3,'Research');
CREATE TABLE Employee(id INTEGER PRIMARY KEY,name TEXT NOT NULL,salary INTEGER NOT NULL CHECK(salary>0),departmentId INTEGER NOT NULL REFERENCES Department(id));
INSERT INTO Employee VALUES(1,'Ada',90000,1),(2,'Ben',85000,1),(3,'Cara',85000,1),(4,'Dev',80000,1),(5,'Eli',70000,1),(6,'Fay',75000,2),(7,'Gus',60000,2);
